### ISSUE TITLE
View Templates -> Code

### ISSUE THREAD

**Issue by DavidRieman** [WheelMud/WheelMUD#10]
ViewEngine currently relies on NVelocity to render views.  Those view templates are Practically Code except they completely lack the modern debugging capabilities of actual C# code.  (The stated reason for the NVelocity template existence, was the ability to have non-reboot updates to the view templates.  However, we've proven a means of performing non-reboot updates of actual coded systems as well, so this concern is no longer appropriate.)  We'd like to replace the view rendering with actual code and have that code placed under test.

Ideally, the methods that perform the view rendering should be exposed somehow through MEF; the view engine should become an ISystem that is IRecomposable, to be able to support non-reboot updates.  However, this part can be moved to a later issue if the implementer desires.

**Comment by duaneking** [comment]
NVelocity is actually just a .NET port of a once proprietary Java project that has since been depreciated and "donated" to the Apache foundation. I'm not a fan of it for our needs.

Having actual code would also allow us to better integrate with our plans anyway; the ViewEngine seems sort of heavy for what we want it to do and I find that limiting our desire to make Thing's dynamic.
