### ISSUE TITLE
Look into SpecFlow

### ISSUE THREAD

**Issue by DavidRieman** [WheelMud/WheelMUD#13]
We should see if SpecFlow is something we want to use for this project, by spiking a few 'specs' and raising a discussion.

**Comment by duaneking** [comment]
Glad to see this made an official issue.  Should I just start doing that with my ideas now?

**Comment by DavidRieman** [comment]
Yes I think that's reasonable.

**Comment by axiomatic-io** [comment]
Where did the spikes end up with this issue? SpecFlow is a testing framework I gather?

**Comment by DavidRieman** [comment]
I don't recall doing said spike.  Yes it's a testing framework.  I don't recall why I was interested in it at the time.  Right now, I feel the existing test projects, which allow for running tests in Visual Studio, or with other test tooling, is sufficient.  I may just close this issue.

**Comment by duaneking** [comment]
SpecFlow is AMAZING but you need to learn about TDD to use it correctly.  Since I consider TDD (Test Driven Development) a VITAL skill for every developer, I'm in full support of its use,

**Comment by axiomatic-io** [comment]
@duaneking  Do you have any recommended resources for learning TDD? Books or video content?

**Comment by duaneking** [comment]
BDD aka Behavior Driven Development - The style of testing Specflow advocates - is actually considered a type of TDD.

So learning TDD is somewhat a prerequisite to learning BDD; There are debates on this and what should come first - some people think that since BDD advocates for use cases first its less testing and more planning and functional requirements - but as somebody who was formally trained in both I consider BDD to be a more advanced form of TDD.

https://www.amazon.com/exec/obidos/ASIN/0321146530/ is considered - for lack of a better term - the "bible" on the topic of TDD.

Once you understand the basics - that entire book is dense and honestly I have taught half an hour brown-bags that educated teams on  the basics, even though I own a copy of the book and would rather people read it  - its really simple and most of wht you need to do is done by reading the  specflow basic usage docs once you understand the basic Red-Green-Refactor way of testing and have a CI/CD pipeline built.

**Comment by axiomatic-io** [comment]
Thanks, @duaneking !
