### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by hectorsosajr** [WheelMud/WheelMUD#18]
I found, by accident, Travis CI while browsing other repos here on GitHub. Travis CI integrates with GitHub very smoothly. I tested it with a Winform project I have here on GitHub. I was totally surprised that it worked right off the bat. All you need is to add a .travis.yml file to the repository. My file consisted of just 2 lines; language and solution.

I thought I pass this along.

https://travis-ci.org/

**Comment by DavidRieman** [comment]
Looking into this today  :)

**Comment by DavidRieman** [comment]
Iterated on DavidRieman/WheelMUD to get this up and running (there were tons of unused var warnings it treated as errors, that VS doesn't by default even warn about), and now it works great.  Going to get it running on WheelMUD/WheelMUD too.

Next up will be to add another, because Travis doesn't mimic actual Windows builders.  I read it is possible to hook up more than one, to get multiple build environments covered.

**Comment by DavidRieman** [comment]
We now have windows and non-windows build verification, plus all tests run in NUnit AND MSTest in the AppVeyor environments.
