### ISSUE TITLE
Incompatibility of source code

### ISSUE THREAD

**Issue by mdziczkowski** [WheelMud/WheelMUD#19]
Please make that the code universal and avaliable in form that it can be compiled on any Operating Systems and not just on Windows (not every one has a Windows installed)

**Comment by DavidRieman** [comment]
A Mono effort was underway some time ago.  While I will not be heading up such an effort myself, if another developer wants to get us there, I would be happy to support the endeavor.

**Comment by Altorffer** [comment]
Compatibility does not seem very far off, in fact. Cloning the project, opening WheelMUD.sln and performing a "compile all" in MonoDevelop does not generate any Errors. Just warnings. Quite a few of them but those, for the most part, are related to unused assignments.

**Comment by chadq** [comment]
wheelmud was originally created because there were no native mud servers for windows. its come full circle.

**Comment by mdziczkowski** [comment]
does is planed to create a Whellmud for Linux?

**Comment by duaneking** [comment]
There is no plan to port to Linux as Linux does not have the correct support yet, and to even attempt this would dramatically increase development effort.

**Comment by mdziczkowski** [comment]
@duaneking a platform independant version of Wheelmud could overgo described by you problem ;)

**Comment by duaneking** [comment]
Its not as simple as you, in your ignorance, suggest.  CLR Core still has a lot of work that needs to be done, and Mono is not in a state that can support this last I checked, so any request we port this to Linux when the entire reason this exists is to be a windows only supported MUD is denied, if only due to framework and 
LEGAL issues as the license is windows based and as a result its NOT COMPATIBLE with the GP or any of the other licenses that would need to be supported for compatibility.
