### ISSUE TITLE
Remove all Proprietary Code / Libs from Wheelmud

### ISSUE THREAD

**Issue by duaneking** [WheelMud/WheelMUD#2]
I'm noticing some dll's that are checked in that are NOT open source and not free; this is a huge disservice to the users and while it may still be viable for them to use these under whatever license Wheel Mud has I think its best for everybody if we just remove all code that depends on these and replace them with free/custom/open source options.

One of the big ones seems to be the HoytSoft Services libraries; A fast glance makes me assume we can replace it with TopShelf pretty easily but I think we should just add things that need to be removed to this item.

**Comment by DavidRieman** [comment]
Agreed.  Here are some comments related to the Service libs in particular that I had tracked elsewhere.  (At a glance, I believe TopShelf fulfills these needs.)

"It is possible to build a single application so that it:
* Behaves as a normal Console Application.
* Behaves as a Windows Service when given a particular command-line argument such as -RunAsService (which is only supplied by the windows service manager)
* Behaves as a light Console Application which controls the service instance with command-line arguments such as -StartService -StopService -PauseService -ResumeService.
* Automatically installs itself as a Windows Service as appropriate.
This eliminates the need for a separate installer just for the windows service. This would also remove 4 extra projects from our solution (including all the "HoytSoft" projects which are hard to find information about on the Internet anyway.) We'll then want to rename TestHarness to better reflect the repurposed functionality."

**Comment by duaneking** [comment]
The HoyteSoft stuff also has a license that is incomparable with everything else we use.. so its getting ripped out even if it breaks things in the short term, probably some time today as I have already started the top-shelf work.

I'm actually at the point now where all the tests that passed before still do, and the service itself is starting under topshelf.  Its been about half a decade since I last touched the test code since I was not here during any of that time, but it was literally the last thing I touched before I left so I'm glad it saw some use.  I'm also going to be checking in some updates to it as part of the massive change to rip out the Hoytsoft stuff.

**Comment by duaneking** [comment]
Ok I have a merge request being made right now to fix this at the basic level.  I suspect some things may have been missed but everything that Visual Studio/Reharper detects as  part of our tests still runs green.

**Comment by duaneking** [comment]
This fixes #5

**Comment by hectorsosajr** [comment]
Where you guys able to complete the removal of all the HoytSoft stuff? How's TopShelf working out? I'm curious because I haven't heard about TopShelf before. The little bit I saw looked pretty good.

**Comment by DavidRieman** [comment]
Yes, the TopShelf integration works pretty nicely.  Right now I can take a shell to binDebug and run "wheelmudwindowsservice.exe install --sudo", it elevates for admin and installs.  Then "wheelmudwindowsservice.exe start" starts the service.  Telnet successfully connects.  Can similarly stop the service easily from the commandline before making a new build, etc.

**Comment by DavidRieman** [comment]
Turns out it does every bullet point I was looking for in my original comment, just with different syntax, and way less code than I thought it would have to be.  Note that just running "wheelmudwindowsservice.exe" starts it up as not-a-service console app in interactive mode; perfect.

My minor nitpick right now is that "wheelmudwindowsservice.exe help" output claims the user types "service.exe" instead of the real executable name.

I think we can easily accomplish collapsing the "service" project with the "testharness" as mentioned in issues/15.  :)

**Comment by duaneking** [comment]
Names are minor and can be changed :+1:

**Comment by DavidRieman** [comment]
Closing;  If there were any remaining offenders that are not covered in the current tickets, let's open up specific new tickets.
