### ISSUE TITLE
Eliminate dependencies on paid/throttled technologies

### ISSUE THREAD

**Issue by duaneking** [WheelMud/WheelMUD#33]
One of the big reasons I never work on this anymore, and I'm assuming one of the reasons it never picked up more developers.  is that somebody added requirements for thousands of dollars of proprietary tools we don't have and can't afford to buy, and didn't listen to me when I said that was a bad idea.

This project is effectively DEAD as an open source project due to these limitations.

This includes:
* CodeSmith ($499.00/year)
* RavenDB ($749 /year)
And possibly more.

Visual Studio Community Edition is free and shouldn't be considered a limitation here, but these other bad architectural choices are what is currently keeping me from working on this. Contributors shouldn't have to spend over a thousand dollars to work on a part-time side project, and while I said this at the time I was outvoted..

So I'm either going to fork this project or start from scratch on a new one if the licensing isn't compatible with what I want to do. From the look of it, it may just be better if I start over from scratch.

Using only free and updated MSFT Tools would be a lot better, but I also see the license as a problem - the MSPL is viral but isn't compatible with a lot of nice libs - so while I retain all rights to my own code, I may be forced to start a new project to use all of my ideas if I want to continue my mud development like I do.

If there are any other devs for this project active/alive, please speak up.  I want to know your thoughts on this situation.

**Comment by DavidRieman** [comment]
There's easily several topics here, but I'll try to touch on several at a high level.  I think we could split each topic into their own threads.

> Contributors shouldn't have to spend over a thousand dollars to work on a part-time side project

Agree 100%

CodeSmith:  Yeah, I've never had these tools, and never needed them, since we had good compartmentalization of responsibilities with Hector managing the data stuff.  I really don't like having this as a dependency either now, and of your points I think this is the strongest one.

RavenDB:  I'm no lawyer, but my understanding is that we acquired a free community license for RavenDB, so our cost is $0/year there.  That said, actually sitting down and _properly learning_ how to open, explore, and experiment with a RavenDB has been one of my own mental road blocks, yet I know it's one of the highest priority things we should figure out.  (Alternatively, _IIRC_ one of Hector's goals with the data abstraction layer was to allow an administrator decide which storage tech to use;  like you could replace a lower level with SQL and the higher level "Save" methods wouldn't need to know it.)

To both techs above:  Supposedly a good object or document database could dramatically simplify things and unlock the kinds of rapid development/innovation that would align well with the whole idea of having a MUD in C# to begin with.  I think we could eliminate the need for generated data templates altogether if these things work nearly as simply as, say, file serialization libraries.  So I think we're aligned that we should look into elimination of the CodeSmith dependency - whether that's replacement or retiring as unnecessary.  I'd be happy to hear potential alternative solutions if you have something in mind on the data storage tech end as well.  :)

VS Community Edition:  Yes, I agree we've long held support for free IDE solutions including that, and should always continue to do so.

MS-PL:  I'm still no lawyer, but, I believe MS-PL is way more compatible than many people think.  It's an easy license to comply with.  It's permissive and very compatible with MIT.  It's totally acceptable to, say, fork the code base, make private additions that aren't shared with anyone, and profit from a pay-to-play version of the server, etc.  (Also keep in mind you don't have to ship server code to the users, so theoretically maybe you could utilize/connect components that _weren't_ compatible so long as you didn't decide to ship that server code to anyone.)  If you've got a specific library you want to use that you're bummed you think we can't, I'd love to hear which.  :)

Anyway, there's tons of good stuff here - some of the hardest parts like the Telnet protocol stuff and good, extensible interactive object design paradigms are present - I think we could resurrect the project with some work on the bits above, plus figuring out where those who fork get stuck and fail/forego communications and give up.

**Comment by duaneking** [comment]
I fully agree on using a repository pattern for data storage; Just keep to a known data model for serialization and use the repository pattern for data storage and retrieval.

But I'm also against prioritizing a specific commercial db and I feel like a commercial db shouldn't even be supported in the project until its finished and working in a v1 if the goal is open source.  Just because we have a license, doesnt mean a random contributor does.  Often, they dont, so wthey open it up and things just don't work.. so they move on.,   so I respectfully consider RavenDB to be a cancer in this case.

**Comment by DavidRieman** [comment]
Do you have a data storage solution in mind?  What would you build if you built from scratch?

**Comment by jeanke75** [comment]
I'm not sure if you guys are going to resurrect this or start it from scratch or something completely new, but I might be willing to join in if any of the aforementioned

**Comment by axiomatic-io** [comment]
I get it that Raven has a community (free) license for use to develop projects so that shouldn't be a problem. What I'm unclear about is where CodeSmith is used in the project? Can someone fill me in on the thought process behind including it in the toolchain?

**Comment by DavidRieman** [comment]
I don't recall about CodeSmith off hand.  I thought we were using some T4 template generation instead, which caused some problems.  Such tech would likely have been related to DAL regeneration process or something - One of the big drivers of the project for the longest time (Fasta) was our DAL guy, so I never had to learn much about it, but maybe DAL regeneration is done outside the main solution, if still applicable?

**Comment by DavidRieman** [comment]
So I think this whole thread comes down to "What do we want to do with persistence going forward?"  We can start with defining desires I guess...
* Needs to be easy to save/load data for arbitrary Things and Behaviors (and Effects).
* Needs to support constantly churning code (e.g. adding new properties to Behaviors and such, with an obvious way to specify how to default missing properties when loaded, etc.)
* Needs to be easy for developers who aren't data persistence experts to discover and successfully address said persistence details.  (Maybe persistence hints should be present right on the regular code?)
* Needs to be easy to test (maybe some tests that use reflection to find and save a Thing with every currently developed Behavior attached to it, then load it, verify a few key properties on a few key behaviors, etc) - Well written tests here might help with scenarios like where a property was added but does not have good persistence metadata attached, well before that code ever tries to go into a prod MUD server.
* Needs to be easy to find and load at least Player Things by their name/id; must avoid having to fully load every player that ever existed into memory to find the right Player for a login attempt.  (Possibly we keep the separate [SQLite?] tabling for Players, and/or a few key things?)

Ultimately I hoped a document database like RavenDB would make it trivially easy to save/load arbitrary object trees (like players filled with Behaviors and inventory and all in one fell swoop), but I still haven't done a deep dive to learn the tech properly and see if it really is the magic bullet here.  That said, @duaneking had concerns about using even the free-for-OSS RavenDB and has yet to chime in on alternatives.  I'd like to hear more thoughts on a desirable approach, so I'll open this up to anyone:

Do you have a data storage solution in mind? What would you build if you built from scratch?

(If we want to stick with trying RavenDB for now, we at least need to upgrade the version to the latest free-OSS-supported version, which I think might _not_ be the latest version?  The version we have referenced I believe has a known security issue.)

**Comment by axiomatic-io** [comment]
I think a document style database is good because the code will be dealing with lists of arbitrary length for numerous entities (like inventory for players) and not really relational data. Should we use Nuget to keep dependencies like Raven up to date?

**Comment by axiomatic-io** [comment]
Nevermind I found the Nuget setting on the solution level. I was looking at the project level.

**Comment by hectorsosajr** [comment]
> I don't recall about CodeSmith off hand. I thought we were using some T4 template generation instead, which caused some problems. Such tech would likely have been related to DAL regeneration process or something - One of the big drivers of the project for the longest time (Fasta) was our DAL guy, so I never had to learn much about it, but maybe DAL regeneration is done outside the main solution, if still applicable?

It's been a while since I looked at the code. I'm Fasta. The intention was as you said. I was in the process of moving the DAL templates to T4. That would negate the need for CodeSmith. I passed the baton to David, but I keep an eye on conversations like this one.

**Comment by hectorsosajr** [comment]
> I think a document style database is good because the code will be dealing with lists of arbitrary length for numerous entities (like inventory for players) and not really relational data. Should we use Nuget to keep dependencies like Raven up to date?

That's exactly the reason why I picked a NoSQL database for that data. RavenDb is much easier to use in the .NET world than MongoDb.

**Comment by axiomatic-io** [comment]
I upgraded all the projects to .NET 4.7.2 to prepare for the upgrade of RavenDB and submitted a PR.

**Comment by axiomatic-io** [comment]
Finished the RavenDB upgrade a little while ago. Its not putting the file in the right directory so I have to fix that but everything appears to be working otherwise.

**Comment by duaneking** [comment]
To answer the sudden flurry of questions:

Even if RavendDB has a free licence available, I'm 100% against its use and I do not even have a RavenDB licence myself, so if its a firm requirement for this project then its a hard blocker for me.

CodeSmith was used to autogenerate some T4 template generated code; I'm still 100% against that code generation - I have spoken out against it before - as I feel like we should be writing the code to be extendable and SOLID, and not depending on automation to regenerate it when we want to add something.

The DAL should be using an ORM that support migrations and other best practices, not depending on auto-generation, as I have stated before.

If a Thing/Behavior/Effect was simply dumped to/loaded from disk, that would work.

I wrote a test console before; Not sure what happened to it.

SQLite has free and easily available C# bindings, and its remarkably useful; its been my vote for back-end db in this project and others like it for years for small things.  The problem is that actual running worlds that get big will want to use something else for perf and thats why I advocate for the repository pattern and the future extend-ability it gives things.

I'm against MondoDB with the rage and fury of a thousand suns and I consider it an act of mercy to kill its use in any project I encounter.  Its the absolute worst tool for the job in every instance I have ever  encountered its use, it corrupts your data at load, its not at all ACID Compliant, you cant recover from its errors due to its queue-to-write and its poor design is nothing but a trap for the uneducated and unwary.  For your own protection, stay away from it.

Another option would be http://www.litedb.org/ and I just found that via a 5 second google search.

**Comment by Portalboy** [comment]
Hi, I am a professional Database Administrator and after seeing what @duaneking commented on MongoDB, I felt compelled to log in and post that in my experience he is COMPLETELY CORRECT. 
Mongo is made to be so easy to use for developers, it doesn't have all those 'unnecessary restrictions' like proper object relationships which speed up related data access, or 'bloated features' like advanced locking and blocking mechanics to protect your valuable data from purity issues.

It's an absolute trap and, indeed, not ACID compliant. I have complaints about NoSQL in general, but absolutely against MongoDB. It's both slow and has horrendous design issues which all 'pro mongo' people I know have eventually realized and had to either design a work-around or migrate data platforms. 

Consider MySQL (excellent free option), Microsoft SQL Server Express Edition (free, though with a 10GB size limit), PostgreSQL (free, very feature rich, people love it), SQLite, or if you really must use NoSQL for some reason, avoid MongoDB like the plague. 
But know that everything used to be 'NoSQL' back in the day, that's why the SQL standard was invented - to solve the copious issues that come along with using non-relational, transactionally inconsistent, non-atomic data storage systems. 

But that's just my two cents.

**Comment by Portalboy** [comment]
To address issues of "arbitrary length" data, that can be solved by simply thinking of the data slightly differently. 

You can create a mapping table which holds, following the inventory example, one row for every object in an inventory, with a few columns:
The primary key of the Inventory it belongs to (i.e. which player's inventory)
The primary key of the object, or just the name of the object
Whatever else you need that would be relevant for all objects, like Weight, etc.

If you really want to have document-style storage (which is typically considered an anti-pattern, but useful in some cases nonetheless), you can define JSON or XML data inside most relational databases. That gives you the perks of ACID and massive performance gains of key seeking and joining, whilst retaining the ability to define arbitrary-length data.

There are lots and lots of ways to do this with SQL, which is why that is what the world has been using for decades before this NoSQL goldrush. 

ACID and SQL were invented to save you headaches and make your life MUCH easier, it just takes a little more effort up front in designing the system. It is not the enemy that so many NoSQL fans make it out to be.

**Comment by axiomatic-io** [comment]
Good points by everyone. I'm kind of agnostic. I prefer to use what solves the problem best. Do we want to include a separate server requirement to host the data or use something file based (SQLCE for example)? Are there embedded options for those databases you mentioned?

**Comment by Portalboy** [comment]
I do like the idea of abstracting it to make adding support for various data platforms easy.

Using something small and light like SQLCE as the default option would be nice, and people would be able to commit to add handlers for things like MySQL which could be installed separately on the same machine or another, and have WheelMUD pointed at it. 
Obviously I am just a single person who also just got here, but from both a user and contributor's standpoint, I think that would be a great option.

**Comment by duaneking** [comment]
@Portalboy Is correct and this is EXACTLY why I keep telling everybody USE THE REPOSITORY PATTERN.

https://martinfowler.com/eaaCatalog/repository.html

**Comment by axiomatic-io** [comment]
Correct me if I'm wrong but could we use Entity Framework to do implement that pattern? And seriously, correct me, I don't care if I'm wrong. I want to understand.

**Comment by axiomatic-io** [comment]
I've spent so much time in the web world with CMS platforms that enterprise/architecture patterns get mothballed in my brain.

**Comment by Portalboy** [comment]
Yep, Entity Framework will work for that and is a common choice.
 
For extra credit, my usual recommendation is to be careful using EF's auto-generated queries as a crutch too much since their performance tends to be bad, but that's obviously something that can be fixed later if needed. Most people use them to get started quickly and then go manually write queries for the heaviest operations to speed them up. You can then tell EF to use a specific query or call a specific procedure to get that data. 

Oh, and avoid UUIDs/GUIDs/UNIQUEIDENTIFIER datatypes wherever possible, they SUCK cause they cause mega fragmentation (most DB engines will try to sort them alphabetically in the table to make seeking to them fastest, causing index fragmentation). You want to use INTs, SMALLINTs, BIGINTs wherever humanly possible for your Primary Key columns.

But these are just tips to save you some time down the road. EF can be extremely handy when implemented properly.

**Comment by duaneking** [comment]
I'm actually a big fan of UUID's for primary keys for ultra large data sets, but a 60 petabyte multi dimensional data storage system with audited hardware and the need to track down generated UUID's to a specific network systems card at a given time of day isn't a problem we have (It is a problem I have seen in the wild, though) so I agree, lets not worry about it.

Entity is a good default these days, and I have worked with some very smart people at MSFT that spent a lot of brain cycles working on it.  There are some rough edges but the sharp parts of it have been worn down as long as you are OK with reading the docs.

**Comment by duaneking** [comment]
https://docs.microsoft.com/en-us/ef/efcore-and-ef6/index

**Comment by duaneking** [comment]
But using the ORM is one of many steps; The repository pattern used well would mean that only one provider would use EF and you would still be free to use others via the provided backing interface.

It really depends on how open you want the storage layer to be.  My personal choice is that code should be closed for modification and open for extension.

**Comment by DavidRieman** [comment]
> I do not even have a RavenDB licence myself

If you want a license key in your own name, instead of trusting that we have permission, simply go to https://ravendb.net/license/request/community and make a request.  IIRC when I did this the response email was quite quick. So that part is easily solved, but I am not discounting your other concerns.

I believe the server runs fine without the user having to go through this permission request process.  I don't recall having to actually hook up the license key anywhere, myself.  @axiomatic-io, was that part of the required process of getting the server up and running for you?

(Also there was interesting reading at https://ayende.com/blog/4508/comments-on-ravendb-licensing) 

> so if [RavenDB is] a firm requirement for this project

No, nobody is saying this is a firm requirement, hence all the discussion exploring our options here.

> we should be ... not depending on automation to regenerate it when we want to add something

Agree. Adding persistence for newly coded Behaviors (or changing properties of existing ones) and such should require very little work, no code generation processes, etc.

> SQLite ... remarkably useful; its been my vote

We're using it today as our default backing DB behind our existing repository interfaces, storing things like the table of PlayerRecord. This is certainly useful as an existing means of looking up a player by the name a user typed into telnet, and seeing if the password is correct, etc. 

After that is the part we're currently using RavenDB for: Once authenticated, the real player in-world object is to be loaded from somewhere. The thought was we could persist it easily, with little code, as a single document, regardless of the hundreds of types of Behaviors and such that may be attached to them and their equipment.  That's where we're at, but it's not fully functional (saving works but loading not so much and there's sometimes RavenDB startup issues), and it's not necessarily where we want to be.

> If a Thing/Behavior/Effect was simply dumped to/loaded from disk, that would work.

I'm open to this.  I've procrastinated long enough against sitting down and learning RavenDB properly - maybe it's just not going to happen. XML seralization and such though, are tech I definitely know, and I think the community will grasp easier as well.  Indeed if we abstract the player object persistence well like Fasta wrapped the rest of the DAL in its repository pattern, I think it would not be too hard for people to add other options for swapping in, later in the project.

> MongoDB

Haha, I don't think anyone here has recommended we use this?  I've never had to use it.

---

@Portalboy - Welcome!
> inventory, with a few columns ... can define JSON or XML data inside most relational databases

One cool thing with WheelMUD is that all Things make strong usage of composition to define their Behaviors.  So one small caveat to this strategy is we'd probably also have a table of Behavior/Effect instances tied to each Thing.

I think a key to having any kind of generic serialization approach (JSON/XML and such, whether persisting the result to a file on disk or inside such a "whatever data" table column) will be writing tests that automatically discover and attempt to save and then load each savable behavior and such. Thus as a tinkerer adds a new behavior, they'll immediately learn when they need to add some metadata to the object to avoid blowing up upon save/load.

> Entity Framework

I don't know much about this tech.

**Comment by DavidRieman** [comment]
I've just closed #9 as I think we're definitely not going full NoSQL.

As much as I'd like to jump back into the code with what spare time I can muster, I know I can serve the project much better by spending those moments working on improving community-oriented stuff like documentation restoration and such.

@Portalboy, are you looking to contribute?  Given your experience as a DBA, would you be interested in contributing in said capacity?

**Comment by Portalboy** [comment]
@DavidRieman Sorry for the lul, had a ton going on today. 

I am considering it. My time is very limited but I do think it would be a very interesting project. 
Right now I am really trying to learn a little .NET, but mostly MySQL. I have no experience with SQLCE so probably can't help too much there. 

If MySQL ends up being a serious consideration I could probably contribute with that. That said, I know it is no small matter to add an extra requirement for end-users to install a MySQL instance somewhere. 

As far as .NET though, since I'm a DBA and development is more of a hobby, I only know Ruby and my .NET is currently infant-stage. 
Let me know what you think of this. Thanks!

**Comment by DavidRieman** [comment]
Cool.  If you're interested and find time, I'd be curious what the state of our non-SQLite DBs are right now.  I do see a script at `systemdata\SQL\mySQL` that looks like it sets up tables.  I've logged #45 for this.

**Comment by duaneking** [comment]
I'm against needing to give my email to a for-profit company I would rather have no affiliation with just so they can spam me so I am allowed to use an open source project.

There is also the issue of the current license; It's too restrictive. Yet I don't think it can be changed.

**Comment by DavidRieman** [comment]
> needing to give my email

Then don't.  You don't need to

> current license; It's too restrictive

Are you talking about RavenDB or WheelMUD?  (I dug up an old thread talking about MS-PL here: http://muds.gamedev.com/mudforum/index.php?t=msg&goto=76)  If you're talking about WheelMUD, please open a new thread to discuss what scenario you feel is important that you feel restricted from, and ideally, proposal for a specific license that would accommodate better.  (Ms-PL was originally going to be called "Microsoft Permissive License" due to it's permissiveness.  I'm curious where you're feeling blocked.  Again, if you've got a specific library you want to use that you're bummed you think we can't, I'd love to hear which... In said thread.   Would like to close this one out since it branched so much.

**Comment by gpiedimonte** [comment]
Why implement now RavenDb or other Relational database? 
IMHO the best solution is use simple txt files, or XML or JSON if you prefer.
If some one want use a Relational database or NO-SQL database for a MUD could implement his technological implementation using the public interfaces.

**Comment by pha3z** [comment]
Hey guys, your thread/project caught my attention.  Just chiming in to some thoughts about the whole discussion of:
flat files vs embedded database vs stand-alone server database

One of the primary benefits to using a standalone server-hosted DB engine (as opposed to embedded database or flat files) is concurrency.  You gain the ability to access the database from separate clients and read or modify that data.  For a MUD, this would be useful if you wanted to manipulate user accounts, world data, or myriad other data from a software system not within the MUD itself.  And believe me, there is plenty of reason to want to do things like that.  Having easy eyes on your data and the ability to easily manipulate it is gold.  Flat txt files (though they may seem convenient at first) get very unwieldly when the data grows.

You also get the engine's own benefits like its dump/backup/restore mechanisms.

Using flat files (txt, xml, json) means you completely lose access concurrency, and you even lose indexing (SqlLite, which is an embedded, serverless database gives you indexing benefits).  Probably the single biggest problem with flat text files is passing the ACID test.  If the system crashes, the data is only as good as the last write you performed before the crash.  And if it crashed during a write, the data is corrupted.  With flat files, you have to write a huge amount of tedious logic to make sure that problem doesn't happen.  Standard databases do this out-of-the-box without you thinking about it.

Earlier, it was discussed about the possibility of supporting embedded database systems, (like Lite DB or SqlLite).  This sounds nice if you don't want the mud developer to have to spin up and maintain a separate database.  However, honestly, if someone is going to maintain a data-intensive system such as a MUD, they're fooling themselves if they think they're going to go very far without having some consideration as to their data integrity and data system.  The benefits of using stand-alone database far outweigh the initial startup convenience of an embedded database.

Also, reinforce the Repository pattern mentioned earlier.  It is surprisingly easy to abstract data layer from program logic once you learn the pattern.  It should be done always, everywhere.  It doesn't make sense to have this code entangled.

**Comment by DavidRieman** [comment]
@pha3z You raise some other great points as well.  Thanks for taking the time to write your views here.

Currently we use SQLite by default, behind a Repository pattern, for keeping an indexed list of player names / login info, for starting the login process.  This uses PlayerRecords.  It was built with the ability to choose something like full SQL as the backing engine if you want, through simple configuration.  Though honestly I never tried that, as SQLite is good enough for me.  If the player authenticates into a session successfully, then we move on to loading the associated PlayerBehavior.  As a _proof-of-concept_, this did the work directly with RavenDB, but was meant to be a _temporary_ measure.  Unfortunately we had some issues and this happens to be where development stalled on this front.  Nobody here has suggested we _shouldn't_ use Repository pattern for this part, that's just how it is ATM due to rapid prototyping.  I've filed #47 to rectify how this violates our DAL principles.

(aside: Ideally we'd persist the whole player Thing as the player document instead of loading a PlayerBehavior onto a `new Thing()` -- IIRC we started with just PlayerBehavior to limit scope a little bit on the document-based persistence exploration.)

If we went with flat files for saving PlayerBehaviors and the like, we'd still continue using the PlayerRepository (e.g. SQLite) for the indexed lookup of the PlayerRecord, to then know which actual player Thing to load and attach to the session (via another repository).  The rest of your ACID concerns beyond indexing are totally a huge deal though and indeed I could see those becoming a _huge_ problem down the line.

You reminded me of another big concern with multiplayer games, especially where including player economies - which is item duplication and such.  When I think of how one would have prevented the item duplication bug I found in WoW, _transactions_ to save multiple arbitrary systems states in tandem (or fail, in tandem) would have been one of the best ways to solve it for sure.  Which is something DB systems (including RavenDB) can handle for us but would be _tons_ of work to try to build from scratch.  (Work that I'm not interested in doing.)  For example, if one of our players gives an item to another, we could save them both as one transaction so no item could be duplicated even if we crashed in the middle of it.

So yeah, you got me back to thinking we need to get to a state where RavenDB is working again, and get it behind a Repository, and move forward from there.  If someone wants to avoid RavenDB, I'd be down with supporting multiple choices as the backing system behind the new repository, which one would select via the app.config.

**Comment by pha3z** [comment]
@DavidRieman 

Thanks for sharing the part about using database transactions to save multiple arbitrary system states in tandom.  I hadn't even thought to mention the tremendous value of transactions. **The example about item exchanges saved as a single transaction is an exceptional example of leveraging the power of an ACID database.**

**Comment by pha3z** [comment]
@DavidRieman 

One more thing, is there a doc somewhere explaining why the choice to go with RavenDB was made?  I actually haven't worked with any of the open source nosql databases, so I have no idea what Raven is bringing to the table.

All of my experience has been with open source SQL systems Postgres and Mysql.  I'm aware of the benefits of SqlServer, though I've never used it.  I haven't yet worked on a project that I felt mandated a document database.  Whenever, I've needed document-style data, it's usually been only a subset of my data and I just chuck it into a key-value-pair system in a relational table designed for that.

**Comment by DavidRieman** [comment]
There's a (poorly-formatted) backup copy of one of those conversations at http://muds.gamedev.com/mudforum/index.php?t=msg&goto=257&rid=0

**Comment by DavidRieman** [comment]
Closing since the remaining issues are covered at #43 (RavenDB strategy) and #42 (which is half done already) - and if there are other dependencies we want to change they can be new threads too.
