### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by axiomatic-io** [WheelMud/WheelMUD#34]
I'd like to contribute. How do you recommend I get started?

Sorry about the issue spam, I wasn't sure how to message the project owner.

**Comment by DavidRieman** [comment]
Welcome!  This is a fine place to discuss for now.  I would start by playing around with and exploring what's there so far.  We have a bit of documentation, but we had tons more that we just haven't ported into a GitHub-friendly markdown format or whatnot (including various basic design documents for various features we had in mind).  One idea for a first place to tackle code changes could be finding a Behavior that lacks tests and adding tests.  I might be able to give you some more specific ideas for things to tackle, especially if you have some areas of expertise you want to apply or whatnot.  Historically throughout the project we've ended up getting more drawn in and _finding_ the time when others are also contributing.  You're welcome to discuss what you want to change, and open PRs against this repo or the base.  Thanks!

**Comment by axiomatic-io** [comment]
Where can I find the non-markdown documentation?

**Comment by DavidRieman** [comment]
The old forums content were copied (with very poor formatting) to http://muds.gamedev.com/mudforum/ and is tough to just dig into.  For example, the [OLC discussion](http://muds.gamedev.com/mudforum/index.php?t=msg&goto=262&rid=0&srch=behaviors+design#msg_262) was pretty good but it's hard to find the good stuff on the forum if you don't know what you're looking for.  Only a bit (the World Interaction Story) was made to HTML in the git code Documentation folder as an experiment, looking for a nice way to format it here, but turned out to be way too labor intensive.  And I'm not sure how (if even possible) to link it to render as HTML rather than raw text.  At some point I'll still need to take another stab at bringing the nicer design documents into GitHub, probably with some markdown editing tool to get sections to look like colored telnet output.  Ultimately, figuring out how to get interesting, engaging documentation is high on my priority list for things to do as I get back into the swing of things here.  Among figuring out other ways to make it easier to dive in and contribute.

As is, I wouldn't worry too much about design docs.  Other than tests, another way to get started would be to dig in and find something that is broken and try to fix it.  Where are you at so far?  Have you run the server, connected with a Telnet client and played around a bit with what's there?

**Comment by axiomatic-io** [comment]
I cloned the repo and was able to get everything running on localhost enough to go in and interact with the world. I'll take a look at the tests and any broken spots from the issues list. I really appreciate your help as I get started. Thanks!
