### ISSUE TITLE
Restore player roles, and employ FirstCreatedCharacterIsAdmin setting

### ISSUE THREAD

**Issue by DavidRieman** [WheelMud/WheelMUD#64]
Player character roles have been disabled for some time.  We need to revisit these, thinking again about where they live (perhaps on a new or existing Behavior).

Once repaired, we should implement an app.config settings like "FirstCreatedCharacterIsAdmin" which is true by default.  Normally a new admin will be the first to create a character, before the MUD is even live.  This will make it easier to ensure the MUD starts with a valid administrator.  The messaging around granting the role should be loud and clear.  (It should be easy to disable this setting, if a MUD admin would prefer to have to go straight in to the DB to assign the role manually where needed, for example, if a live MUD absolutely has to reset all player data for some reason.)

**Comment by DavidRieman** [comment]
Player roles have been restored as a single SecurityRoles property persisting with the UserControlledBehavior.  I restored role granting/revoking commands as well.
I still think we should do something like "FirstCreatedCharacterIsAdmin" setting, so leaving this ticket open for that.

**Comment by duaneking** [comment]
I don't like the idea of only security groups. Never did.  But I do like the idea of security claims that can be verified through a chain of trust and allows admins to give fine grain controls.  The simple version of this is a security tag system that defines roles and perms given based on the role granted. Groups could work on top of this, as collections of claims/roles. The problem is I see groups as heavy handed compared to roles but roles can be so fine grained, they can get complicated fast on any given server.

The choice would ultimately be theirs, however.

**Comment by DavidRieman** [comment]
Split up to a fresh issue on the base repo, and tagged you in a new discussion
