### ISSUE TITLE
Try embracing full NoSQL data approach

### ISSUE THREAD

**Issue by DavidRieman** [WheelMud/WheelMUD#9]
Right now we use a combination of relational DB (SQL) and RavenDB (NoSQL).  However, we no longer have a dedicated DBA focusing on the project, and the SQL complexity is substantial.  We would like to reduce complexity around data, and try out embracing a full NoSQL solution for everything.  Right now that's looking like we should really dig into RavenDB.  If this works, saving players will be largely just "save this Thing as a Player document, including all its children (like inventory) and behaviors".  Loading players would find the Player document, ensure the credentials match, load that Thing and associate their session.  (If this doesn't work well, we could store credentials as separate short documents like they are in the relational DB now, just may as well be in RavenDB as well for consistency.)  Then we can eliminate most of the projects and such in the Data solution folder.

**Comment by duaneking** [comment]
1. I'm comfortable with any database stuff we need as I am a "full stack" developer. If I do not know it, I will just learn it. That said, I have a lot of experience with "normal" transnational databases and "eventually consistent" NoSql databases.
2. I'm against RavenDB due to its increased cost and its increasingly commercial nature that severely limits what people can do with it, or worse, how big worlds on muds can get.  I don't think its right for us to use a DB that limits the amount of RAM they are "licensed" to use as that effectively limits the size of a world or the number of users it can support. It just doesn't seem fair to users.
3. The current DB stuff is a mess as we seem to have a system that requires we use third party tools that are not free or easily accessible. I'm sure its going to need some love.

My dream? We have a minimal IDataRepository interface that allows serialization of types without getting hung up on where the data ends up, and we can create plugins as needed to support data storage with it for any data back-end we need, using a simple and effective solution just to get traction.

**Comment by DavidRieman** [comment]
"...RavenDB... the "free" version is broken for anything if the size we need as they limit licensing to the number of cores or ram you want to use... That just doesn't fit well with the goals of this project."
I wasn't aware of such limitations being imposed on the free-for-open-source-projects version that we got.  That said, it doesn't look like we could upgrade to the latest as things do look to be changed.  At best, we'd have to track down the last version that was free for us, and figure out if it has such limitations.  That said, I'm not attached to RavenDB, and would love to consider other "Just save this whole object tree" options.  My biggest concerns right now:
* We can't afford to have to keep a DAL trained specifically about every behavior, every effect. etc. - Especially in the late game of community building / sharing Behaviors and things...  Many Behaviors should be able to be completely isolated pieces of code and not have to be accompanied by DAL code, IMO.
* Behavior/effects implementations and such change during development - deserialization should do its best to fulfill properties into the version of the object that the code has, and should not be hard to mitigate when there are breaking changes (like a RoomBehavior's property name just changed and we still need to be able to load existing rooms).

**Comment by duaneking** [comment]
1. I'm not even aware of what version or license the RavenDB stuff is.  I only checked the website and did seem research on its cost and found http://ravendb.net/Buy/More saying that for even 1gb of RAM used they want a monthly subscription of $7/usd.  That seems really high to me and it also seems to go against the goals of Wheel-mud

2. Behaviors should serialize in a way that should be DAL interdependent IMHO, I don't want to have  to update serialization code for every different class or object, so in my mind just giving them a common serialization interface and using meta-programming (like .NET already does for the SerilizableAttribute) is the  answer.

3. That sounds more like module versioning to me, and could be mitigated with versioned loaders, correct?
